// Customizable Area Start
exports.GetdataContentType = "application/json";
exports.GetdataEndPoint = "bx_block_settings/settings/get_settings";
exports.GetdataAPiMethod = "GET";
exports.LocationdataContentType = "application/json";
exports.LocationdataEndPoint = "account_block/accounts/personal_information";
exports.LocationdataAPiMethod = "PUT";
exports.GetPercentageContentType = "application/json";
exports.GetPercentageEndPoint = "account_block/accounts/profile_percentage";
exports.GetPercentageAPiMethod = "GET";
exports.GetSendotpContentType = "application/json";
exports.GetSendotpEndPoint = "account_block/accounts/set_accout_type";
exports.GetSendotpAPiMethod = "GET";
exports.getHoursApiUrl = "bx_block_dashboard/dashboards/daily_working_hours";
exports.getReportDetailsUrl = "bx_block_dashboard/dashboards/incident_details";
exports.uploadReportDetailsUrl = "bx_block_dashboard/dashboards/panic_incidents/";
exports.postdataAPiMethod = "POST";
exports.incidentNumber = "Incident Number";
exports.respondedAt = "Responded at";
exports.arrivalAt = "Arrival at incident";
exports.timing = "On Scene timing";
exports.location = "Location";
exports.yourLoaction = "Your Location";
exports.cfArrival = "Confirm your Arrival"
exports.cancel = "CANCEL"
exports.confirm = "CONFIRM"
exports.closeIncident = "Close incident !";
exports.instruction = "Before closing the incident, you need to submit the incident report.";
exports.subInstruction = "Click on close button, this will take you to Add incident report screen";
exports.sphara = "SPHARA";
exports.noEmergencies = "There are currently no emergencies close you";
exports.away = "m away";
exports.incidetDetails = "Click here to know about incident details";
exports.getDirection = "GET DIRECTION";
exports.worked = "Hours worked";
// Customizable Area End